name: 'listify-actions'
description: 'Generate and merge all directories to the specified file.'
author: 'zzz'
branding:
  icon: 'align-left'
  color: 'blue'
inputs:
  github_token:
    required: true
  listify:
    description: 'listify config file'
    required: true
    default: './listify.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.listify }}
