name: 'listify-actions'
description: 'When you push document . It can generated list of contents to specified file.'
author: 'zzz'
branding:
  icon: 'align-left'
  color: 'blue'
inputs:
  github_token:
    required: true
  listify:
    description: 'listify options'
    required: false
    default: './'
  commit_msg:
    description: 'commit message'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.listify }}
